### ISSUE TITLE
Wishes

### ISSUE THREAD

**Issue by webmastak** [NimbleArchitect/termtyper#1]
It’s good to make the terminal itself become active when entering the command.
Or if the terminal is not open, it starts and the command is inserted.

And as I understand it, there is no functionality to edit a snippet?

Finding snippets is certainly good, but I would also like a list of snippets, for example.
Here is a similar functionality in the screenshot:
![go_terminal](https://i.imgur.com/hpmOZuL.png)
[Go Terminal](http://rungoterminal.com/)

**Comment by NimbleArchitect** [comment]
the program should switch to the previous window before typing the command, if this is not happening please raise a bug ticket.

editing is currently not implemented but is planned.

I like the idea of an always visible list, I'll add it to my todo list

**Comment by webmastak** [comment]
"I like the idea of an always visible list, I'll add it to my todo list" 👍
