### ISSUE TITLE
Bug -  termtyper does not switch to the previous window

### ISSUE THREAD

**Issue by webmastak** [NimbleArchitect/termtyper#2]
The program does not switch to the previous window before entering the command.

**Comment by NimbleArchitect** [comment]
which os/desktop manager are you using?

**Comment by webmastak** [comment]
Manjaro Linux
Gnome Shell

**Comment by webmastak** [comment]
I use the tilix terminal and it’s much more convenient to use the bookmark functionality, than reinvent the wheel. 😆
![tilix bookmarks](https://i.imgur.com/AL5RnUQ.png)
![tilix bookmarks search](https://i.imgur.com/x5NKUyK.png)

**Comment by NimbleArchitect** [comment]
switched to using gtk to minimise the window, instead of using alt-tab
